<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="DotNetEnv" Version="3.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.18.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\SatelliteEmergencyHub.Application.csproj" />
		<ProjectReference Include="..\SatelliteEmergencyHub.Infrastructure\SatelliteEmergencyHub.Infrastructure.csproj" />
	</ItemGroup>

</Project>